### ISSUE TITLE
How to search for values without mispapireport?

### ISSUE THREAD

**Issue by TheDr1ver** [remg427/misp42splunk#128]
In previous iterations of using this tool I found that I relied heavily on the mispapireport command, but I see in the most recent publication the command has been removed and my dashboards no longer work. I suppose this leads to 3 questions that hopefully you can answer:

What was the reason for removing the ability to communicate direclty with the API via the mispapirepot command?

Will it be coming back?

I used to use the following snippets in my dashboards to search MISP for a specific value, but if I attempt to use mispgetioc I now get an error stating that the value field is not supported. How can I search the MISP API directly for a specific value under the current MISP42Splunk version?
```
| mispapireport misp_instance=$misp_instance$ mode=p includeEventTags=1 $to_ids_flag$
[| makeresults | eval value="$SearchItem$" | return value]
| table misp_timestamp misp_id misp_category misp_type misp_value misp_comment misp_event_info misp_event_id misp_tag misp_to_ids
```

**Comment by remg427** [comment]
Hi, thank you for your email and use of misp42
In version 3.1.x I worked to ensure the code is compatible with python3. I have also introduced a new custom command mispgetevent leveraging /events/restSearch
To simplify the maintenance I decided to drop the custom command mispapireport but I have integrated the option json_request in both mispgetioc and mispgetevent so all previous functionalities are preserved even if yes it would require some adaptation 
```
|mispgetioc misp_instance=ops json_request="{}" to_ids=t geteventtag=t limit=1000
```
I hope this wil solve your issues otherwise I will update mispgetioc (and mispgetevent) to restore the functionality
I didn't know the use of the tokens, could you explain your example?
