### ISSUE TITLE
Misp42Splunk App user needs the "list_storage_passwords" capability.

### ISSUE THREAD

**Issue by reachuttam** [remg427/misp42splunk#135]
The Misp42Splunk App user needs the "list_storage_passwords" capability. This capability lets the user list and view the /storage/passwords endpoint, lets the user perform GETs. The admin_all_objects capability must be added to the role for the user to perform POSTs to the /storage/passwords endpoint.

In our environment these capabilities are enabled only for admins. Is there a way to redesign the App where the App user does not need the "list_storage_passwords" capability.

**Comment by remg427** [comment]
Hello,
I would like misp42splunk vetted for cloud so following splunk [documentation](https://dev.splunk.com/enterprise/docs/releaseapps/appinspect/cloudvettingguidelines/vetappsandaddons/)

# Development requirements for Splunk Cloud

If you are developing an app or add-on for installation in Splunk Cloud, do the following:  
...
    **Ensure that all credentials that are used and stored by the app, such as API keys, account passwords, and Base64-encoded private keys, are encrypted using the storage/passwords REST endpoint**. For more information, see Access endpoint descriptions in the REST API Reference Manual and Setup page example with user credentials.  
...

and on [REST endpoint documentation](https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTaccess)
```
https://<host>:<mPort>/services/storage/passwords
```
Create or update user credentials, or list credentials for all users.

**Authorization**
The **list_storage_passwords capability** is required for the GET operation. The **admin_all_objects** capability is required for the POST operation. 

If someone could help to solve this dead lock, this will be very appreciate

otherwise an alternative is to go back to pure lookup table storing also API key but then it is only for on-site deploiement
