### ISSUE TITLE
Display MISP Decay score in Splunk

### ISSUE THREAD

**Issue by qanniej** [remg427/misp42splunk#160]
Hello, 

We are using decay model to score indicators in MISP. 

Currently, the decay score is not displayed in Splunk. I want to request this as a feature as it will help us greatly. This can be obtained through the API using parameter 'include_decay_score=True' when calling pymisp.search()

https://www.misp-project.org/2019/09/12/Decaying-Of-Indicators.html
https://pymisp.readthedocs.io/en/latest/modules.html 
https://misp.gitbooks.io/misp-book/content/pymisp/

**Comment by remg427** [comment]
Hello, 
thanks for raising this request.
Actually parameters in JSON request have become numerous so I don't plan to implement every pairs as parameters of misp custom commands. Even if misp42splunk does not use pymisp for the moment (I am waiting to drop compatibility with python 2.7 as some splunk instances in version 7.x have still only this version and I am impacted), I have introduced since some versions a parameter json_request to pass the JSON query like you would use it directly with the API (you can use MISP REST client to build the correct request payload. don't forget to escape ".
this is for the request to be able to use any of the params MISP API supports for both endpoints /events/restSearch and /attributes/restSearch.
Then use param output=raw so the results will appear in JSON format.
It might be more interesting for your use case to use mispcollect misp_instance=... endpoint=attributes (default) json_rerquest="valid JSON query".
The command returns matching MISP events as splunk events. 
Hope this clarify and answer to your request

**Comment by ag-michael** [comment]
@remg427 I also tried to do this with such a query:

`| mispgetioc misp_instance=default json_request="{\"event_id\":\"1234\",\"includeDecayScore\":\"true\",\"includeContext\":\"true\",\"includeSightings\":\"true\",\"includeEventTags\":\"true\"}"  output=raw`

It doesn't output the decay score as it does with the pymisp API, is it something I'm doing wrong with the json_request?

**Comment by remg427** [comment]
Hi with similar command I get decay_score entry in _raw field
